name: random_color_app
description: A test task app.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0-38.0.dev <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  google_fonts: ^3.0.1
  solid_lints: ^0.0.12

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets\fonts\Montserrat-Regular.ttf
        - asset: assets\fonts\Montserrat-SemiBold.ttf
          weight: 600
